### ISSUE TITLE
naive

### ISSUE THREAD

**Issue by Dafrok** [Dafrok/thrash#1]

**Comment by ZhongCitizen** [comment]
笑看研究生中医粉是如何给自己的大学丢脸的案例：
[刚看到一个例子，211大学研究生说：感冒优先吃感冒灵，中暑优先喝藿香正气水](https://tcmexposed.github.io/2019/07/13/%E4%B8%BA%E4%BB%80%E4%B9%88%E6%9C%89%E4%BA%BA%E8%AE%A4%E4%B8%BA%E4%B8%AD%E5%8C%BB%E8%8D%AF%E6%9C%89%E6%95%88-747290077.html)

[中医师非蠢即坏拿自杀事件抹黑感冒药](https://tcmexposed.github.io/2019/05/15/%E5%A6%82%E4%BD%95%E8%AF%84%E4%BB%B7-%E5%9B%9E%E9%A1%BE%E4%B8%AD%E8%8D%AF%E6%B3%A8%E5%B0%84%E5%89%82%E7%A0%94%E5%8F%91%E7%9A%84%E5%8E%86%E5%8F%B2-%E4%B8%BA%E4%B8%AD%E8%8D%AF%E6%B3%A8%E5%B0%84%E5%89%82%E8%AF%B4%E4%B8%80%E4%BA%9B%E8%AF%9D-684384831.html)

[中医理论博士逻辑连小学生都不如](https://tcmexposed.github.io/2019/03/30/%E4%B8%AD%E5%8C%BB-%E4%B8%BA%E4%BD%95%E4%B8%8D%E5%BA%9F%E5%8C%BB%E9%AA%8C%E8%8D%AF-636641943.html)

[中医科研人员睁着眼睛说瞎话，明明不推荐使用的论文拿出来证明针灸疗效毫无疑问](https://tcmexposed.github.io/2018/11/19/%E8%AF%B7%E5%AD%A6%E5%8C%BB%E7%9A%84%E4%B8%93%E4%B8%9A%E4%BA%BA%E5%A3%AB%E6%9D%A5%E8%AF%B4%E4%B8%80%E8%AF%B4-%E5%88%B0%E5%BA%95%E4%B8%AD%E5%8C%BB%E6%9C%89%E6%B2%A1%E6%9C%89%E5%AD%98%E5%9C%A8%E7%9A%84%E4%BB%B7%E5%80%BC-534311558.html)


最后，本帖作者 @Dafrok ，根本就不识字,ICD 说白了就是个词典收录了传统医学的名词：
https://www.zhihu.com/question/296305024/answer/499625632

https://www.zhihu.com/question/296402829/answer/502467363
